### ISSUE TITLE
Any ETA on when this repo will receive the code?

### ISSUE THREAD

**Issue by josesimoes** [STMicroelectronics/STM32CubeF7#1]
BTW: excellent move on providing the Cube packages on GitHub! Well done! 👏

**Comment by ALABSTM** [comment]
Dear Jose Simoes,

Thank you for your interest. We are presently working on this. We aim to have all STM32Cube packages available on Github soon.

We cannot share a date for the moment. We will keep you informed.

With regards

**Comment by ALABSTM** [comment]
Dear Jose,

STM32CubeF7 package (v1.15.0) has just been published on GitHub. We hope this addresses your request. In such case this issue could be closed. Thank you for your patience.

With regards,

**Comment by josesimoes** [comment]
Thanks! 👏👍
