### ISSUE TITLE
Basically all of the stm32f7xx_hal_eth.h macros are just copy-pasta'd from H7 and using H7 registers

### ISSUE THREAD

**Issue by HTRamsey** [STMicroelectronics/STM32CubeF7#101]
F7 registers != H7 registers

**Comment by TOUNSTM** [comment]
Hello @holden-zenith,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With Regards,

**Comment by TOUNSTM** [comment]
Hello @holden-zenith,

I've tried to do an analysis on my own and I can't find the problem you mentioned. In order to enable a better analysis of this problem, could you please give us more details.

Thank you again for your contribution.

With regards,

**Comment by holden-zenith** [comment]
for example
`#define ETH_DMA_NORMAL_IT                 ETH_DMACIER_NIE`
There is no ETH_DMACIER_NIE in stm32f767xx.h.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 169492

**Comment by mek363** [comment]
Can someone clarify which macros are affected by this?

**Comment by HTRamsey** [comment]
I think this fix was merged

**Comment by mek363** [comment]
@HTRamsey thanks, was it this commit? https://github.com/STMicroelectronics/stm32f7xx_hal_driver/commit/5af4f7192a9331d27e5e90feed5e7cebc3f1356c

Is there any explanation of what incorrect behavior we might see without this fix? Or would we see compile-time errors because the referenced defines are not found?

**Comment by HTRamsey** [comment]
Should just be compile-time errors because they were all referencing H7 registers.

**Comment by ALABSTM** [comment]
Fixed in commit 5ff42d9979458a6426d67783c8ea2b2c7baee8d6
