### ISSUE TITLE
Can't Use IS_TIM_CCX_INSTANCE in CMSIS periph file using LL drivers by default

### ISSUE THREAD

**Issue by HTRamsey** [STMicroelectronics/STM32CubeF7#108]
IS_TIM_CCX_INSTANCE uses TIM_CHANNEL_1 ... TIM_CHANNEL_6 which is defined in HAL but LL defines them as LL_TIM_CHANNEL_CH1 ... LL_TIM_CHANNEL_CH6 so currently it is required to copy over the definitions when only using LL.

**Comment by KRASTM** [comment]
ST Internal Reference: 195285

**Comment by HTRamsey** [comment]
Nice, thanks!
