### ISSUE TITLE
ETH: Missing ETH_MACCR_CSTF in cmsis header and driver

### ISSUE THREAD

**Issue by HTRamsey** [STMicroelectronics/STM32CubeF7#115]
CSTF is mentioned in the documentation (taken from RM0410) but not provided in the cmsis header or eth driver. It is, however, correctly added to H7 as ETH_MACCR_CST.
![image](https://github.com/STMicroelectronics/STM32CubeF7/assets/68555040/7da3b428-d661-4e53-b704-cab07a3f0b27)

Also, HAL_ETH_SetMDIOClockRange is never called anywhere.

**Comment by HTRamsey** [comment]
Also a quick question, is `ETH_MACDMAConfig` supposed to configure to reset values or are these configurations just arbitrarily chosen? For example, `RetryTransmission` is disabled making RD high instead of its reset value of low. The H7 driver enables it by default, which leaves RD at its reset value of low.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 143308

**Comment by TOUNSTM** [comment]
Fixed in 30b30b27616d01af3fa11e0ba1662500bb6b5b3a

**Comment by TOUNSTM** [comment]
Fixed in 0495bf0fda6f592b034a4267f8e7c7b816e4196e
