### ISSUE TITLE
inconsistent board names

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/STM32CubeF7#2]
I suggest using consistent board names. Some board names start with 32F while other start with STM32F, and the official product names use STM32* prefix.
The first time I tried to use CubeMX it took me 30 minutes to figure out in was not a missing ZIP package but names in CubeMX were different. It was just bad initial experience.
Also, why no dash before DISCOVERY?

**Comment by ALABSTM** [comment]
Dear Tomasz Jastrzębski,

Please note that this organization is meant to publish STM32 software and to promote co-development. Hence, issues have to be related to the software, once published.

Any other topic shall be addressed to the [STM32 Community](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus). Thank you for your comprehension.

With regards
