### ISSUE TITLE
White noise when we are calling BSP_AUDIO_IN_OUT_Init(uint16_t InputDevice, uint16_t OutputDevice, uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)

### ISSUE THREAD

**Issue by nusret103** [STMicroelectronics/STM32CubeF7#29]
Dear,

When i call the function

```
uint8_t BSP_AUDIO_IN_OUT_Init(uint16_t InputDevice, uint16_t OutputDevice, uint32_t AudioFreq, uint32_t BitRes, uint32_t ChnlNbr)
```
with parameters
```
inputDevice == INPUT_DEVICE_INPUT_LINE_1
```
```
(BSP_AUDIO_IN_OUT_Init(inputDevice, OUTPUT_DEVICE_HEADPHONE,
                                      FS_, DEFAULT_AUDIO_IN_BIT_RESOLUTION,
                                      DEFAULT_AUDIO_IN_CHANNEL_NBR)
```
I am getting white noise on ```OUTPUT_DEVICE_HEADPHONE``` when I am using ```INPUT_DEVICE_INPUT_LINE_1```!

What I can do to use line1 like input and headphones like output this is a very crucial issue to be resolved. Let us know what we can do here?

Nusret

**Describe the set-up**
 *  DISCO-STM32F746
 *  MbedStudio 1.3.0
 *  Audio codec in use wm8994

**Comment by RKOUSTM** [comment]
Hi @nusret103,

Thank you for your contribution.

Actually, the point you raised has already been raised in another issue #26. It has been internally fixed. The fix will be published in the frame of a future publication.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 93452

**Comment by RKOUSTM** [comment]
ST Internal Reference: 93458

**Comment by nusret103** [comment]
@RKOUSTM Thank you for your feedback.

Did you have any time frame when this issue will be ready for testing?

With respect,

**Comment by RKOUSTM** [comment]
Hi @nusret103,

Thank you for your contribution. 
This update will be integrated in the future firmware package release (STM32F7 version v1.16.0)  firmware package.
Stay tuned.

Thank you again for your contribution.

With regards,
