### ISSUE TITLE
Different defines at Ethernet peripheral configuration

### ISSUE THREAD

**Issue by Danarrow** [STMicroelectronics/STM32CubeF7#44]
Dear Sir and Madam,

i had to change some defines in stm32f7xx_hal_conf.h generated by CubeMx because ethernet does not work when starting up with connected Ethernet on STM32F777 with DP83848I PHY. I copied and pasted the defines from stm32f4xx_hal_conf.h which was also generated by CubeMx. After the changes everythings works fine.

Here are my changes on PHY_SR, PHY_SPEED_STATUS and PHY_DUPLEX_STATUS:  

```
/* Section 4: Extended PHY Registers */
...
#define PHY_SR                          ((uint16_t)0x10U/*0x1FU*/)    /*!< PHY status register Offset             */
#define PHY_MICR                        ((uint16_t)0x11U)    /*!< MII Interrupt Control Register                  */
#define PHY_MISR                        ((uint16_t)0x12U)    /*!< MII Interrupt Status and Misc. Control Register */

#define PHY_LINK_STATUS                 ((uint16_t)0x0001U)  /*!< PHY Link mask                                   */
#define PHY_SPEED_STATUS                ((uint16_t)0x0002U/*0x0004U*/)  /*!< PHY Speed mask                               */
#define PHY_DUPLEX_STATUS               ((uint16_t)0x0004U/*0x0010U*/)  /*!< PHY Duplex mask                      */
...
```

Could it be that the code generation on CubeMx of stm32f7 is buggy when configuring the extended PHY registers? Or am i doing something wrong?

Kind Regards

**Comment by ASELSTM** [comment]
Hi @Danarrow,

As this issue is not related to software published within this repository but rather to ecosystem (CubeMX tool, CubeIDE tool), please allow me to close it.

Thank you for your comprehension and thank you again for your contribution. We are looking forward to reading from you again.

With regards,
