### ISSUE TITLE
HAL MMC card initialization always fails

### ISSUE THREAD

**Issue by nickstoughton** [STMicroelectronics/STM32CubeF7#45]
**Setup**
 * Nucleo-F746ZG board, but present for at least all F7xx processors (and probably many others)
 * Found using gcc 10.1

**Problem**
Any attempt to call `MMC_InitCard()` will fail

**How To Reproduce**
1.Attach an eMMC card (1-bit, 4-bit or 8-bit data paths, it will not make a difference) to a`SDMMC` port (NOTE, eMMC cards use the JEDEC MMC protocol, and not the SD Card protocol).

2.Attempt to initialize it. This call will fail under all circumstances.

**Patch**
Please see attached patch
[patch.tar.gz](https://github.com/STMicroelectronics/STM32CubeF7/files/6672500/patch.tar.gz)

**Comment by ASELSTM** [comment]
Hi @nickstoughton,

Thank you for your contribution and for the proposed fix. We are actually aware about the point you raised out and are working on fixing it. The fix will be made available in the frame of a future release. 
We cannot share a date for the moment. So stay tuned and thank you once more for your contribution and for your patience.

With regards

**Comment by ASELSTM** [comment]
ST Internal Reference: 83264

**Comment by ASELSTM** [comment]
Hi @nickstoughton,

This issue has been fixed in the frame of version **v1.16.2** of the STM32CubeF7 published some time ago. Please allow me then to close it.

With regards,
