### ISSUE TITLE
Typo in ART_ACCLERATOR_ENABLE 

### ISSUE THREAD

**Issue by josesimoes** [STMicroelectronics/STM32CubeF7#58]
**Describe the bug**
There is a typo in ART_ACCLERATOR_ENABLE define. It's missing an E here ART_ACC**E**LERATOR_ENABLE.
The misspelled word is at: stm32f7xx_hal_conf_template.h  and stm32f7xx_hal.c (line 141).

**Comment by ASELSTM** [comment]
ST Internal Reference: 120367

**Comment by ASELSTM** [comment]
Hi @josesimoes,

Thank you for your contribution. This issue has been fixed in the frame of version v1.17.0 of the STM32CubeF7. Please allow me then to close this thread.

With regards,
