### ISSUE TITLE
GPIO_AF9_TIM13 is unused

### ISSUE THREAD

**Issue by KamilDuljas** [STMicroelectronics/STM32CubeF7#83]
In macro IS_GPIO_AF(AF) we double checked AF9_TIM12 instead of AF9_TIM13. All macros in whole file are invalid.

https://github.com/STMicroelectronics/STM32CubeF7/blob/7e354cf248d84d84424e852ab012b345e3155640/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_gpio_ex.h#L462

**Comment by TOUNSTM** [comment]
Hello @KamilDuljas,

Thank you for your report. An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you again for you report.
With regards,
