### ISSUE TITLE
can't download folder

### ISSUE THREAD

**Issue by Amjed2000** [STMicroelectronics/STM32CubeF7#86]
i would download the folder of code but i can't

**Comment by picli3** [comment]
do this:
![Peek 2023-03-26 11-15](https://user-images.githubusercontent.com/11140497/227789229-d370edd9-3bcf-4a8c-8e57-662fa484e14c.gif)
when it downloads go to the folder and that's it

**Comment by RJMSTM** [comment]
Hello @Amjed2000 

You can use the command `git clone https://github.com/STMicroelectronics/STM32CubeF7.git`

If you have succeeded to download the file, please allow me to close the issue.

BeST Regards,
Rania
