### ISSUE TITLE
F756: Conitnious mode does not work on ADC with particular settings

### ISSUE THREAD

**Issue by KamilDuljas** [STMicroelectronics/STM32CubeF7#89]
Nucleo-F756ZG
STM32CubeIDE 1.12.0

I choosed Vrefint channel as model.

When I use ``conversion mode`` - ``EOC flag at the end of single channel conversion`` for ADC1 for one channel, a program read value once and then does not update anymore.

![image](https://user-images.githubusercontent.com/87798948/231738208-bb1d714d-0b6c-4389-82cb-146032eb04fd.png)

On screen I highlighted one option: End of conversion selection. When i set  ``EOC flag at the end of single channel conversion`` it doesn't work. When I change it on ``EOC flag at the end of all conversions`` it works ok.

My code:
```
int main(void)
{
  
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  
  MX_ADC1_Init();
  MX_USART3_UART_Init();
  
  HAL_ADC_Start(&hadc1);
  
  while (1)
  {
 
      uint32_t value2 = HAL_ADC_GetValue(&hadc1);
      float voltage2 = 3.3f * value2 / 4096.0f;
      printf("Vref = %lu (%.3f V)\n", value2, voltage2);
      
      //__HAL_ADC_CLEAR_FLAG(&hadc1,ADC_FLAG_EOC); // Optional but does not work
      
     HAL_Delay(250);
   }
}
```

In my opinion: ``End Of Conversion Selection`` should not be have impact on continious mode in this case., but even if, it should be work on both options. In manual, there's no information about impact EOC flag on ``continious mode``. We read about ``continious mode``:
![image](https://user-images.githubusercontent.com/87798948/231742165-dfb50915-ed84-4be3-bb81-2a7e413f2d8a.png)

I tested it also on 2 channels on ADC1 - IN0 and Vrefint

**Comment by KamilDuljas** [comment]
Any information about this?

**Comment by RJMSTM** [comment]
Hello @KamilDuljas,

Sorry for my tardy reply, I'm still investigating I will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension. 

With regards,
Rania

**Comment by RJMSTM** [comment]
Hello @KamilDuljas,

Would you please give us more details about how you got this issue? And please share snippet of the code you have used to reproduce this problem.

With regards,

**Comment by KamilDuljas** [comment]
Hello I'm recently out of office and I think that I can give update within 30 days.

**Comment by KamilDuljas** [comment]
I found the solution:

![image](https://github.com/STMicroelectronics/STM32CubeF7/assets/87798948/4180babc-67ca-4a9b-bef0-ad17e16ebd37)

Se I must disable overrun feature if i try use continous conversion without dma
