### ISSUE TITLE
Inconsistent information about overrun detection in ADC

### ISSUE THREAD

**Issue by KamilDuljas** [STMicroelectronics/STM32CubeF7#90]
In reference manual for stm32Fx6,
 chapter 15.8.2 we read:

...When EOCS = 1, ``overrun detection is automatically enabled``. Thus, each time a conversion is complete, EOC is set and the ADC_DR register can be read. The overrun management is the same as when the DMA is used..

But in register map we read:

Bit 10 EOCS: End of conversion selection This bit is set and cleared by software.
0:The EOC bit is set at the end of each sequence of regular conversions. ``Overrun detection is enabled only if DMA=1.``
1: The EOC bit is set at the end of each regular conversion. Overrun detection is enabled.

**Comment by RJMSTM** [comment]
Hello @KamilDuljas,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,

**Comment by RJMSTM** [comment]
Hello @KamilDuljas,

In RM 0.385 section 15.8.2 
![image](https://github.com/STMicroelectronics/STM32CubeF7/assets/113367897/e3af0f96-8fbd-4b7f-85b2-fe720e2f4511)
 
When **EOCS = 1**, **overrun detection is automatically enabled**

it's the same think in register map we read

![image](https://github.com/STMicroelectronics/STM32CubeF7/assets/113367897/cb4ea5bd-aec9-49e8-bd42-27fb7e1a8f9a)
 
**The Overrun detection is enabled** when the **EOCS=1**

Best regards,
Rania

**Comment by KamilDuljas** [comment]
Hi, this issue is about overrun management.

"The overrun management is the same as when the DMA is used.."

Versus

"Overrun detection is enabled only if DMA=1."

What's true? Overrun management works always or not?

**Comment by RJMSTM** [comment]
Hello @KamilDuljas 

This description states that ADC overrun detection mechanism is the same (data register write while no previous read acknowledge)
whatever data fetch by DMA (EOCS = 0 and DMA = 1) or fetch by CPU (EOCS = 1).

**Comment by KamilDuljas** [comment]
Ok thanks, I understood now.
