### ISSUE TITLE
ETH_UpdateDescriptor() uses ETH_RX_BUF_SIZE define instead of user supplied value

### ISSUE THREAD

**Issue by Maashau** [STMicroelectronics/STM32CubeF7#93]
ETH_InitTypeDef has user supplied member RxBuffLen. In ETH_UpdateDescriptor() ETH_RX_BUF_SIZE is used instead:
https://github.com/STMicroelectronics/STM32CubeF7/blob/6a3b9bb8d09839f365ba83a6cf5823ae5f5226db/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c#L1234
https://github.com/STMicroelectronics/STM32CubeF7/blob/6a3b9bb8d09839f365ba83a6cf5823ae5f5226db/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c#L1238

Also in ETH_DMARxDescListInit():
https://github.com/STMicroelectronics/STM32CubeF7/blob/6a3b9bb8d09839f365ba83a6cf5823ae5f5226db/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c#L3000

This makes RxBuffLen cause confusion and makes it pretty useless as it has to be the same value as the define.

**Comment by ASELSTM** [comment]
ST Internal Reference: 157139
