### ISSUE TITLE
SD_read - SCB_InvalidateDCache_by_Addr issue

### ISSUE THREAD

**Issue by Jason0926Ni** [STMicroelectronics/STM32CubeF7#95]
When Buffer is not 32-byte aligned, SD_Read will invalidate the Data Cache according to the following code. 
When calculating alignedAddr, the program will add some extra memory addresses to the front, which will cause problems with the data in those memory addresses.

\Middlewares\Third_Party\FatFs\src\drivers\sd_diskio_dma_rtos_template_bspv1.c
\Middlewares\Third_Party\FatFs\src\drivers\sd_diskio_dma_rtos_template_bspv2.c
```

#if (ENABLE_SD_DMA_CACHE_MAINTENANCE == 1)
                /*
                the SCB_InvalidateDCache_by_Addr() requires a 32-Byte aligned address,
                adjust the address and the D-Cache size to invalidate accordingly.
                */
                alignedAddr = (uint32_t)buff & ~0x1F;
                SCB_InvalidateDCache_by_Addr((uint32_t*)alignedAddr, count*BLOCKSIZE + ((uint32_t)buff - alignedAddr));
#endif

```

**Comment by TOUNSTM** [comment]
Hello @Jason0926Ni ,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,

**Comment by ASELSTM** [comment]
ST Internal Reference: 157163

**Comment by TOUNSTM** [comment]
Hello @Jason0926Ni,

First we would like to thank you for your report. In fact, `alignedAddr ` is used only for cache invalidation, it is not used for buffer data read/write.

As this issue is invalid, please allow me thus to close this thread. Thank you fir your comprehension.

With regards,
