### ISSUE TITLE
Wrong description about HAL_IWDG_DEFAULT_TIMEOUT

### ISSUE THREAD

**Issue by almightychang** [STMicroelectronics/STM32CubeF7#97]
The comment about `HAL_IWDG_DEFAULT_TIMEOUT` seems to be outdated:
https://github.com/STMicroelectronics/STM32CubeF7/blob/fe78bad77db8206ff7b65e6d0d07fca912756404/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c#L120-L129

The comments suggests to multiply by 1000 to convert into milliseconds. However, it is already multiplied by 1000U. HAL code assumes it as milliseconds just as below:

https://github.com/STMicroelectronics/STM32CubeF7/blob/fe78bad77db8206ff7b65e6d0d07fca912756404/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c#L203

**Comment by ALABSTM** [comment]
Hi @almightychang,

Looks like there is a slight misunderstanding. The descriptive comment says that the timeout value **has already been multiplied**  by `1000` to be in milliseconds. **No need** to multiply it again at the user application level.

https://github.com/STMicroelectronics/STM32CubeF7/blob/fe78bad77db8206ff7b65e6d0d07fca912756404/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c#L126

I hope this removes the ambiguity. Please let me know whether this answers your question.

With regards,

**Comment by ALABSTM** [comment]
Hi @almightychang,

I hope my previous comment helped clarify the point. Please allow me to close this thread. Thank you again for your post.

With regards,
